// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BseRecentlyFriendList.proto

package com.xinqihd.sns.gameserver.proto;

public final class XinqiBseRecentlyFriendList {
  private XinqiBseRecentlyFriendList() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BseRecentlyFriendListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string uids = 1;
    java.util.List<String> getUidsList();
    int getUidsCount();
    String getUids(int index);
    
    // optional bool battlefriend = 2 [default = false];
    boolean hasBattlefriend();
    boolean getBattlefriend();
  }
  public static final class BseRecentlyFriendList extends
      com.google.protobuf.GeneratedMessage
      implements BseRecentlyFriendListOrBuilder {
    // Use BseRecentlyFriendList.newBuilder() to construct.
    private BseRecentlyFriendList(Builder builder) {
      super(builder);
    }
    private BseRecentlyFriendList(boolean noInit) {}
    
    private static final BseRecentlyFriendList defaultInstance;
    public static BseRecentlyFriendList getDefaultInstance() {
      return defaultInstance;
    }
    
    public BseRecentlyFriendList getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.internal_static_com_xinqihd_sns_gameserver_proto_BseRecentlyFriendList_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.internal_static_com_xinqihd_sns_gameserver_proto_BseRecentlyFriendList_fieldAccessorTable;
    }
    
    private int bitField0_;
    // repeated string uids = 1;
    public static final int UIDS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList uids_;
    public java.util.List<String>
        getUidsList() {
      return uids_;
    }
    public int getUidsCount() {
      return uids_.size();
    }
    public String getUids(int index) {
      return uids_.get(index);
    }
    
    // optional bool battlefriend = 2 [default = false];
    public static final int BATTLEFRIEND_FIELD_NUMBER = 2;
    private boolean battlefriend_;
    public boolean hasBattlefriend() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public boolean getBattlefriend() {
      return battlefriend_;
    }
    
    private void initFields() {
      uids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      battlefriend_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < uids_.size(); i++) {
        output.writeBytes(1, uids_.getByteString(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBool(2, battlefriend_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < uids_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(uids_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getUidsList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, battlefriend_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.internal_static_com_xinqihd_sns_gameserver_proto_BseRecentlyFriendList_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.internal_static_com_xinqihd_sns_gameserver_proto_BseRecentlyFriendList_fieldAccessorTable;
      }
      
      // Construct using com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        uids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        battlefriend_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList.getDescriptor();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList getDefaultInstanceForType() {
        return com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList.getDefaultInstance();
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList build() {
        com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList buildPartial() {
        com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList result = new com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          uids_ = new com.google.protobuf.UnmodifiableLazyStringList(
              uids_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.uids_ = uids_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.battlefriend_ = battlefriend_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList) {
          return mergeFrom((com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList other) {
        if (other == com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList.getDefaultInstance()) return this;
        if (!other.uids_.isEmpty()) {
          if (uids_.isEmpty()) {
            uids_ = other.uids_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureUidsIsMutable();
            uids_.addAll(other.uids_);
          }
          onChanged();
        }
        if (other.hasBattlefriend()) {
          setBattlefriend(other.getBattlefriend());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureUidsIsMutable();
              uids_.add(input.readBytes());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              battlefriend_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string uids = 1;
      private com.google.protobuf.LazyStringList uids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureUidsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          uids_ = new com.google.protobuf.LazyStringArrayList(uids_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getUidsList() {
        return java.util.Collections.unmodifiableList(uids_);
      }
      public int getUidsCount() {
        return uids_.size();
      }
      public String getUids(int index) {
        return uids_.get(index);
      }
      public Builder setUids(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUidsIsMutable();
        uids_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addUids(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureUidsIsMutable();
        uids_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllUids(
          java.lang.Iterable<String> values) {
        ensureUidsIsMutable();
        super.addAll(values, uids_);
        onChanged();
        return this;
      }
      public Builder clearUids() {
        uids_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addUids(com.google.protobuf.ByteString value) {
        ensureUidsIsMutable();
        uids_.add(value);
        onChanged();
      }
      
      // optional bool battlefriend = 2 [default = false];
      private boolean battlefriend_ ;
      public boolean hasBattlefriend() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public boolean getBattlefriend() {
        return battlefriend_;
      }
      public Builder setBattlefriend(boolean value) {
        bitField0_ |= 0x00000002;
        battlefriend_ = value;
        onChanged();
        return this;
      }
      public Builder clearBattlefriend() {
        bitField0_ = (bitField0_ & ~0x00000002);
        battlefriend_ = false;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.xinqihd.sns.gameserver.proto.BseRecentlyFriendList)
    }
    
    static {
      defaultInstance = new BseRecentlyFriendList(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.xinqihd.sns.gameserver.proto.BseRecentlyFriendList)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_xinqihd_sns_gameserver_proto_BseRecentlyFriendList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_xinqihd_sns_gameserver_proto_BseRecentlyFriendList_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033BseRecentlyFriendList.proto\022 com.xinqi" +
      "hd.sns.gameserver.proto\"B\n\025BseRecentlyFr" +
      "iendList\022\014\n\004uids\030\001 \003(\t\022\033\n\014battlefriend\030\002" +
      " \001(\010:\005falseB\034B\032XinqiBseRecentlyFriendLis" +
      "t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_xinqihd_sns_gameserver_proto_BseRecentlyFriendList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_xinqihd_sns_gameserver_proto_BseRecentlyFriendList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_xinqihd_sns_gameserver_proto_BseRecentlyFriendList_descriptor,
              new java.lang.String[] { "Uids", "Battlefriend", },
              com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList.class,
              com.xinqihd.sns.gameserver.proto.XinqiBseRecentlyFriendList.BseRecentlyFriendList.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
