sudo: false
#addons:
#  apt:
#    sources:
#    - ubuntu-toolchain-r-test
#    packages:
#    - gcc-4.8
#    - g++-4.8

# Use gcc-4.8
#install:
#- export CXX="g++-4.8" CC="gcc-4.8";

compiler: gcc
language: c
script:
  - ./make.sh
